name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
      if: always()
    - run: docker build -t playwright_demo .    
    - run: docker run -it -d --name demoContainer playwright_demo /bin/bash
    - run: sudo docker cp demoContainer:./e2e/allure-results allure-results
    - uses: actions/upload-artifact@master
      with:
          name: allure-results
          path: allure-results
    - uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
          ref: gh-pages 
          path: gh-pages   
    - uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
           allure_results: allure-results
           gh_pages: gh-pages
           allure_report: allure-report
           allure_history: allure-history
    - uses: peaceiris/actions-gh-pages@v2
    